# Generated by Django 4.2.30 on 2026-07-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_barrio_alter_cafe_options_alter_cafe_barrio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='summary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
