# Generated by Django 4.2.30 on 2026-07-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_barrio_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
