# Generated by Django 6.0.6 on 2026-07-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("barrio", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("rating", models.IntegerField()),
                ("has_good_medialunas", models.BooleanField(default=False)),
            ],
        ),
    ]
