# Generated by Django 4.2.30 on 2026-07-07 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio_name', models.CharField(max_length=50, unique=True)),
                ('comuna', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['-rating', 'name']},
        ),
        migrations.AlterField(
            model_name='cafe',
            name='barrio',
            field=models.CharField(choices=[('PAL', 'Palermo'), ('STL', 'San Telmo'), ('REC', 'Recoleta'), ('BOC', 'La Boca'), ('BEL', 'Belgrano')], default='PAL', max_length=3),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
