# Generated by Django 6.0.6 on 2026-07-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
