# Generated by Django 6.0.6 on 2026-07-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0007_reviewer_comment_delete_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewer",
            name="join_date",
            field=models.DateField(null=True),
        ),
    ]
