# Generated by Django 6.0.6 on 2026-07-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0008_reviewer_join_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
