# Generated by Django 6.0.6 on 2026-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0010_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="recommendation_count",
            field=models.IntegerField(default=0),
        ),
    ]
