# Generated by Django 6.0.6 on 2026-07-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0012_tag_alter_cafe_options_remove_cafe_rating_cafe_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cafes.cafe'),
        ),
    ]
