# Generated by Django 6.0.6 on 2026-07-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0013_alter_review_cafe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['-name']},
        ),
    ]
