# Generated by Django 6.0.6 on 2026-07-29 18:23

from django.db import migrations


def transfer_data(apps, schema_editor):
    Cafe = apps.get_model('cafes', 'Cafe')
    Barrio = apps.get_model('cafes', 'Barrio')

    for cafe in Cafe.objects.all():
        name_str = cafe.get_barrio_display()
        barrio_obj, created = Barrio.objects.get_or_create(name=name_str)
        cafe.new_barrio = barrio_obj
        cafe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0015_cafe_new_barrio'),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
