# Generated by Django 6.0.6 on 2026-07-29 18:23

from django.db import migrations
import apps
from models import Cafe


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0015_cafe_new_barrio'),
    ]

    operations = [
    ]

def transfer_data(apps, schema_editor):
    apps.get_model('cafes','Cafe')
    apps.get_model('cafes','Barrio')

    for x in Cafe.new_barrio
